#!/bin/bash
# An example of how to run the Virtual ADM3A Terminal
# when using native serial ports.
#
# Usage: adm3as <tty> <baud>
#
# Assumes that https://github.com/durgadas311/adm3a.git was cloned
# into ${HOME}/git. Adjust paths if you use a different location.

JAR1=${HOME}/git/adm3a/ADM3Atty.jar
JAR2=${HOME}/git/adm3a/src/jserialcomm/jSerialComm-2.9.3.jar

exec java -cp ${JAR1}:${JAR2} ADM3Atty "${@}"
